modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Virtuoel/Pehkui/issues"
[[mods]]
modId="pehkui"
version="${file.jarVersion}"
displayName="Pehkui"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pehkui/"
logoFile="pehkui_icon.png"
authors="Virtuoel"
description='''
Allows resizing of most entities.
'''
[[mixins]]
config="pehkui.mixins.json"
